#!/usr/bin/env python

env = SConscript("godot-cpp/SConstruct")

env.Append(CPPPATH=["include"])

sources = [
    "src/eco_node.cpp",
    "src/register_types.cpp",
    "src/my_node.cpp",
]

library = env.SharedLibrary(
    target="bin/libecosim",
    source=sources,
)

env.NoCache(library)
Default(library)
